export const products = ["Embifi", "Malhotra", "HeyEV", "HeyEV Battery"];

export const PRODUCT_MAP = {
  embifi: {
    table: "loan_booking_embifi",
    cols: {
      partnerLoanId: "partner_loan_id",
      lan: "lan",
      customerName: "customer_name",
      mobileNumber: "mobile_number",
      panNumber: "pan_number",
      approvedLoanAmount: "approved_loan_amount",
      emiAmount: "emi_amount",
      address: "applicant_address",
      city: "dealer_city",
      state: "applicant_state",
      product: "product",
      lender: "lender",
      tenure: "loan_tenure_months",
      aadhar: "applicant_aadhaar_no",
      dob: "applicant_dob",
      status: "status",
      accountNumber: "account_no",
      ifsc: "ifsc_code",
      dealerName: "dealer_name",
    },
    manual: {
      table: "manual_rps_embifi_loan",
      cols: {
        id: "id",
        lan: "lan",
        dueDate: "due_date",
        status: "status",
        emiAmount: "emi",
        interestAmount: "interest",
        principalAmount: "principal",
        openingBalance: "opening",
        closingBalance: "closing",
        remainingEmiCount: "remaining_emi",
        remainingInterest: "remaining_interest",
        remainingPrincipal: "remaining_principal",
        paymentDate: "payment_date",
        dpd: "dpd",
        remainingAmount: "remaining_amount",
        extraPaid: "extra_paid",
      },
    },
  },
  malhotra: {
    table: "loan_booking_ev",
    cols: {
      partnerLoanId: "partner_loan_id",
      lan: "lan",
      customerName: "customer_name",
      mobileNumber: "mobile_number",
      panNumber: "pan_card",
      approvedLoanAmount: "loan_amount",
      emiAmount: "emi_amount",
      address: "CONCAT_WS(' ', address_line_1, address_line_2)",
      city: "village",
      state: "state",
      product: "product",
      lender: "lender",
      tenure: "loan_tenure", // ✅ correct
      aadhar: "aadhar_number",
      dob: "borrower_dob",
      status: "status",
      bankName: "bank_name",
      accountNumber: "account_number",
      ifsc: "ifsc",
      tradName: "trade_name",
      gstNumber: "gst_no",
      dealerName: "dealer_name",
    },
    manual: {
      table: "manual_rps_ev_loan",
      cols: {
        id: "id",
        lan: "lan",
        dueDate: "due_date",
        status: "status",
        emiAmount: "emi",
        interestAmount: "interest",
        principalAmount: "principal",
        openingBalance: "opening",
        closingBalance: "closing",
        remainingEmiCount: "remaining_emi",
        remainingInterest: "remaining_interest",
        remainingPrincipal: "remaining_principal",
        paymentDate: "payment_date",
        dpd: "dpd",
        remainingAmount: "remaining_amount",
        extraPaid: "extra_paid",
      },
    },
  },
  heyev: {
    table: "loan_booking_hey_ev",
    cols: {
      partnerLoanId: "partner_loan_id",
      lan: "lan",
      customerName: "customer_name",
      mobileNumber: "mobile_number",
      panNumber: "pan_card",
      approvedLoanAmount: "loan_amount",
      emiAmount: "emi_amount",
      address: "CONCAT_WS(' ', address_line_1, address_line_2)",
      city: "village",
      state: "state",
      product: "product",
      tenure: "loan_tenure",
      lender: "lender",
      aadhar: "aadhar_number", // fixed
      dob: "borrower_dob", // fixed
      status: "status", // fixed
      bankName: "bank_name",
      accountNumber: "account_number",
      ifsc: "ifsc", // fixed
      dealerName: "dealer_name",
    },
    manual: {
      table: "manual_rps_hey_ev",
      cols: {
        id: "id",
        lan: "lan",
        dueDate: "due_date",
        status: "status",
        emiAmount: "emi",
        interestAmount: "interest",
        principalAmount: "principal",
        openingBalance: "opening",
        closingBalance: "closing",
        remainingEmiCount: "remaining_emi",
        remainingInterest: "remaining_interest",
        remainingPrincipal: "remaining_principal",
        paymentDate: "payment_date",
        dpd: "dpd",
        remainingAmount: "remaining_amount",
        extraPaid: "extra_paid",
      },
    },
  },
  heyev_battery: {
    table: "loan_booking_hey_ev_battery",
    cols: {
      partnerLoanId: "partner_loan_id",
      lan: "lan",
      customerName: "customer_name",
      mobileNumber: "mobile_number",
      panNumber: "borrower_pan_card",
      approvedLoanAmount: "loan_amount",
      emiAmount: "emi_amount",
      address: "CONCAT_WS(' ', address_line_1, address_line_2)",
      city: "village",
      state: "state",
      product: "product",
      lender: "lender",
      aadhar: "aadhar_no",
      dob: "dob",
      status: "loan_status",
      bankName: "bank_name",
      accountNumber: "account_number",
      ifsc: "ifsc_code",
      tradName: "trade_name",
      gstNumber: "gst_number",
      dealerName: "dealer_name",
    },
    manual: {
      table: "manual_rps_hey_ev_battery",
      cols: {
        id: "id",
        lan: "lan",
        dueDate: "due_date",
        status: "status",
        emiAmount: "emi",
        interestAmount: "interest",
        principalAmount: "principal",
        openingBalance: "opening",
        closingBalance: "closing",
        remainingEmiCount: "remaining_emi",
        remainingInterest: "remaining_interest",
        remainingPrincipal: "remaining_principal",
        paymentDate: "payment_date",
        dpd: "dpd",
        remainingAmount: "remaining_amount",
        extraPaid: "extra_paid",
      },
    },
  },
};
